name: Update Files
on:
  push:
  workflow_dispatch:
concurrency:
  group: update-files
  cancel-in-progress: true
jobs:
  generatetex:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        listings: [listings, minted]
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
        with:
          submodules: recursive
          path: 'code'
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
      - name: Update npm
        run: npm i -g npm@latest
      - run: npm i npm@latest
      - name: Make generator available globally
        working-directory: ${{ github.workspace }}/code/generator-latex-template
        run: |
          npm install
          npm link
          npm install -g yo
      - run: mkdir /tmp/ltg
      - name: Generate template
        shell: bash
        working-directory: /tmp/ltg
        run: |
          yo latex-template\
           --githubpublish\
           --docker=reitzig\
           --documentclass=ieee\
           --ieee_variant=conference\
           --papersize=a4\
           --latexcompiler=pdflatex\
           --bibtextool=bibtex\
           --texlive=2021\
           --language=en\
           --font=default\
           --listings=${{ matrix.listings }}\
           --cleveref=true\
           --enquotes=csquotes\
           --tweak_outerquote=babel\
           --todo=pdfcomment\
           --examples=true\
           --howtotext=false
        env:
          yeoman_test: true
      - name: Prepare files
        working-directory: /tmp/ltg
        run: |
          if [ "${{ matrix.listings }}" == "minted" ]; then
            mv paper.tex paper-conference-minted.tex
          else
            mv paper.tex paper-conference.tex
          fi

          # remove files which should not be overwritten

          # the LICENSE of the repository should be kept
          rm LICENSE

          # latexmkrc alternates between including and excluding "--shell-escape"; we just want to keep one version of it
          rm latexmkrc

          # copy everything
          cp -r * ${{ github.workspace }}/code/

          cd ${{ github.workspace }}/code/
          git status

          sleep $[ ( $RANDOM % 30 )  + 1 ]s
      - name: Commit changes
        uses: EndBug/add-and-commit@v8
        with:
          message: 'Update files based on generated files by template generator'
          committer_email: actions@github.com
          pull: '--rebase --autostash'
          push: true
          cwd: 'code'
  update:
    runs-on: ubuntu-latest
    needs: [generatetex]
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - run: |
          cp paper-conference.tex paper.tex
      - name: Commit changes
        uses: EndBug/add-and-commit@v8
        with:
          message: 'Update files based on generated files by template generator'
          committer_email: actions@github.com
          pull: '--rebase --autostash'
          push: true
  publish:
    runs-on: ubuntu-latest
    needs: [update]
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver-opts: network=host
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx
      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: localhost:5000/name/app:latest
      - name: Set up Git repository
        uses: actions/checkout@v2
      - run: |
          mkdir /tmp/out
      - name: Build paper-conference.tex
        run: docker run -v $(pwd):/work/src -v /tmp/out:/work/out localhost:5000/name/app:latest work "latexmk paper-conference.tex"
      - name: Build paper-conference-minted.tex
        run: docker run -v $(pwd):/work/src -v /tmp/out:/work/out localhost:5000/name/app:latest work "latexmk paper-conference-minted.tex"
      - run: |
          mkdir publish
          cp /tmp/out/*.pdf publish/
          cp paper.tex publish/
          cp README.md publish/
          cp .github/_config.yml publish/
      - uses: actions/upload-artifact@v2
        with:
          name: publish
          path: publish/
      - name: Deploy
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./publish
          enable_jekyll: true
